#pragma once

// logs
#define MAX_LOG_LEN 64
#define LOG_QUEUE_SIZE 64
#define LOG_RING_SIZE 30
#define LOG_TASK_STACK_SIZE 2000
#define LOG_TASK_CORE 1

// wifi
#define AP_SSID_MAX_LEN 18
#define SCAN_TIME_MIN 150
#define SCAN_TIME_MAX 200
#define FILTER_MASK WIFI_PROMIS_FILTER_MASK_MGMT | WIFI_PROMIS_FILTER_MASK_DATA
#define FILTER_MASK_CTRL 0
#define COLOR_SD_INIT_NOT_FINISHED 0xF800
#define COLOR_SD_INIT_FINISHED 0x07E0
#define PACKET_QUEUE_SIZE 1000
#define PACKET_PROCESSOR_STACK_SIZE 5000
#define PACKET_PROCESSOR_CORE 1
// packet
#define COLOR_PACKET 0xD69A
#define COLOR_PROBE_REQ 0x07FF
#define COLOR_PROBE_RES 0x867D
#define COLOR_BEACON 0x07FF
#define COLOR_AUTH 0xFDA0
#define COLOR_ASSOC COLOR_AUTH
#define COLOR_REASSOC COLOR_AUTH
#define COLOR_DEAUTH 0xF883
#define COLOR_EAPOL 0xFEA0
#define COLOR_DATA 0xB7E0
// sta
#define COLOR_STA_CONNECTING 0x35A6
#define COLOR_STA_RECONNECTING 0x35A6
#define COLOR_STA_DISCONNECTING 0xF940
#define COLOR_STA_ADDED 0xB7E0

// sd
#define SD_QUEUE_SIZE 64
#define SD_TASK_STACK_SIZE 4000
#define SD_TASK_CORE 1
#define COLOR_FOUND_SD 0x07E0
#define COLOR_NO_SD 0xF800
#define COLOR_PCAP_FILE_OPENED 0xFFFF
#define FLUSH_INTERVAL 3500
#define FLUSH_TASK_STACK_SIZE 2000
#define FLUSH_TASK_CORE 1

// display
#define MAIN_MENU_UPDATE_INTERVAL 1000
#define LOG_MENU_UPDATE_INTERVAL 100
#define COLOR_AP_BEACON_NOT_CAPTURED 0xF800
#define COLOR_AP_WPA23_BEACON_CAPTURED 0x87E0
#define COLOR_AP_WPA3_BEACON_CAPTURED 0xFFE0
#define COLOR_AP_WPA2 0xCF7B
#define COLOR_AP_OPEN 0x07FF

// main
#define UPDATE_TASK_STACK_SIZE 3000
#define UPDATE_TASK_CORE 1
#define BUTTON_TASK_STACK_SIZE 4000
#define BUTTON_TASK_CORE 1
#define BUTTON_TICK_INTERVAL 10
#define UPDATE_TASK_INTERVAL 1000
#define DEAUTH_INTERVAL 100
#define STA_AP_UPDATE_TASK_STACK_SIZE 3000
#define STA_AP_UPDATE_TASK_CORE 1
#define DEAUTH_TASK_STACK_SIZE 2000
#define DEAUTH_TASK_CORE 0
#define DETECTED_DROPPED_PACKETS_COLOR 0xF883

// mon thing
#define MONITOR_TASK_STACK_SIZE 2000
#define MONITOR_TASK_CORE 1
#define STAT_BAR_COLOR 0xFEA0